/**
 * chat-memory.ts — Base template with chat memory and context
 *
 * Platform constants (source of truth: deployed smart contracts):
 *   - Deploy fee: 120 FET (read dynamically, can change via multi-sig)
 *   - Graduation target: 30,000 FET -> auto DEX listing
 *   - Trading fee: 2% -> 100% to protocol treasury (NO creator fee)
 */

import type { AgentTemplate } from "../registry.js";

// Environment-based URL resolution (production is default, set AGENT_LAUNCH_ENV=dev for dev)
const PROD_API_URL = 'https://agent-launch.ai/api';
const DEV_API_URL = 'https://launchpad-backend-dev-1056182620041.us-central1.run.app';
const RESOLVED_API_URL = process.env.AGENT_LAUNCH_API_URL ??
  (process.env.AGENT_LAUNCH_ENV === 'dev' ? DEV_API_URL : PROD_API_URL);

export const template: AgentTemplate = {
  name: "chat-memory",
  description: "Chat agent with conversation memory — recommended starting point",
  category: "General",
  variables: [
    { name: "agent_name", required: true, description: "Name of the agent" },
    {
      name: "description",
      required: true,
      description: "Short description of what this agent does",
    },
    {
      name: "memory_size",
      default: "10",
      description: "Number of messages to remember per user",
    },
  ],
  dependencies: ["requests"],
  secrets: ["AGENTVERSE_API_KEY", "AGENTLAUNCH_API_KEY", "AGENT_ADDRESS"],
  code: `#!/usr/bin/env python3
"""
{{agent_name}} — AgentLaunch Chat Memory Agent
Generated by: agentlaunch scaffold {{agent_name}} --type chat-memory

Platform constants (source of truth: deployed smart contracts):
  - Deploy fee: 120 FET (read dynamically, can change via multi-sig)
  - Graduation target: 30,000 FET -> auto DEX listing
  - Trading fee: 2% -> 100% to protocol treasury (NO creator fee)
"""

from uagents import Agent, Context, Protocol
from uagents_core.contrib.protocols.chat import (
    ChatAcknowledgement,
    ChatMessage,
    EndSessionContent,
    TextContent,
)
try:
    from uagents_core.contrib.protocols.chat import create_protocol as _create_chat
except ImportError:
    _create_chat = None
try:
    from uagents_core.contrib.protocols.chat import chat_protocol_spec as _chat_spec
except ImportError:
    _chat_spec = None

import json
import os
from collections import defaultdict
from datetime import datetime
from typing import Dict, List
from uuid import uuid4

# ==============================================================================
# CONFIG
# ==============================================================================

AGENTLAUNCH_API = os.environ.get("AGENTLAUNCH_API", "${RESOLVED_API_URL}")
MEMORY_SIZE = {{memory_size}}

BUSINESS = {
    "name": "{{agent_name}}",
    "description": "{{description}}",
    "version": "1.0.0",
}

# ==============================================================================
# CONVERSATION MEMORY
# ==============================================================================

class ConversationMemory:
    """Store recent messages per user for context."""

    def __init__(self, max_messages: int = MEMORY_SIZE) -> None:
        self._history: Dict[str, List[Dict]] = defaultdict(list)
        self._max = max_messages

    def add(self, user_id: str, role: str, content: str) -> None:
        self._history[user_id].append({
            "role": role,
            "content": content,
            "timestamp": datetime.utcnow().isoformat(),
        })
        if len(self._history[user_id]) > self._max:
            self._history[user_id] = self._history[user_id][-self._max:]

    def get(self, user_id: str) -> List[Dict]:
        return list(self._history[user_id])

    def clear(self, user_id: str) -> None:
        self._history[user_id] = []

    def summary(self, user_id: str) -> str:
        history = self.get(user_id)
        if not history:
            return "No conversation history."
        lines = [f"- {m['role']}: {m['content'][:100]}" for m in history[-5:]]
        return "\\n".join(lines)

# ==============================================================================
# REPLY HELPER
# ==============================================================================

async def reply(ctx: Context, sender: str, text: str, end: bool = False) -> None:
    content = [TextContent(type="text", text=text)]
    if end:
        content.append(EndSessionContent(type="end-session"))
    try:
        await ctx.send(
            sender,
            ChatMessage(timestamp=datetime.utcnow(), msg_id=uuid4(), content=content),
        )
    except Exception as e:
        ctx.logger.error(f"Failed to send reply: {e}")

# ==============================================================================
# MAIN AGENT
# ==============================================================================

memory = ConversationMemory(max_messages=MEMORY_SIZE)
agent = Agent()
chat_proto = _create_chat() if _create_chat else Protocol(spec=_chat_spec)

@chat_proto.on_message(ChatMessage)
async def handle_chat(ctx: Context, sender: str, msg: ChatMessage) -> None:
    # Send acknowledgement
    try:
        await ctx.send(
            sender,
            ChatAcknowledgement(
                timestamp=datetime.utcnow(), acknowledged_msg_id=msg.msg_id
            ),
        )
    except Exception as e:
        ctx.logger.error(f"Failed to send ack: {e}")

    # Extract text from message
    text = " ".join(
        item.text for item in msg.content if isinstance(item, TextContent)
    ).strip()[:2000]

    if not text:
        await reply(ctx, sender, "Please send a message.", end=True)
        return

    lower = text.lower()

    # Help command
    if lower in ("help", "?"):
        await reply(
            ctx,
            sender,
            f"**{BUSINESS['name']}** v{BUSINESS['version']}\\n\\n"
            f"{BUSINESS['description']}\\n\\n"
            f"Commands: help, history, clear",
        )
        return

    # History command
    if lower == "history":
        summary = memory.summary(sender)
        await reply(ctx, sender, f"**Recent conversation:**\\n{summary}")
        return

    # Clear command
    if lower == "clear":
        memory.clear(sender)
        await reply(ctx, sender, "Conversation history cleared.", end=True)
        return

    # Store user message
    memory.add(sender, "user", text)

    # Get context for response
    history = memory.get(sender)
    context_msgs = len(history) - 1  # Exclude current message

    # Generate response (customize this!)
    response = (
        f"I received your message: '{text[:100]}'\\n\\n"
        f"I have {context_msgs} previous messages in memory.\\n\\n"
        f"This is a template — customize the response logic in handle_chat()."
    )

    # Store assistant response
    memory.add(sender, "assistant", response[:200])

    await reply(ctx, sender, response, end=True)

@chat_proto.on_message(ChatAcknowledgement)
async def handle_ack(ctx: Context, sender: str, msg: ChatAcknowledgement) -> None:
    ctx.logger.debug(f"Ack from {sender[:20]} for msg {msg.acknowledged_msg_id}")

agent.include(chat_proto, publish_manifest=True)

if __name__ == "__main__":
    agent.run()
`,
};
