/**
 * chat-memory.ts — Base template with persistent memory, LLM, and chat protocol
 *
 * This is the default template for all agents created with `npx agentlaunch`.
 * It provides a solid foundation: conversation memory that survives restarts,
 * ASI1-mini LLM for intelligent responses, and domain-specific system prompts.
 *
 * Platform constants (source of truth: deployed smart contracts):
 *   - Deploy fee: 120 FET (read dynamically, can change via multi-sig)
 *   - Graduation target: 30,000 FET -> auto DEX listing
 *   - Trading fee: 2% -> 100% to protocol treasury (NO creator fee)
 */

import type { AgentTemplate } from "../registry.js";

// Environment-based URL resolution (production is default, set AGENT_LAUNCH_ENV=dev for dev)
const PROD_API_URL = 'https://agent-launch.ai/api';
const DEV_API_URL = 'https://launchpad-backend-dev-1056182620041.us-central1.run.app';
const RESOLVED_API_URL = process.env.AGENT_LAUNCH_API_URL ??
  (process.env.AGENT_LAUNCH_ENV === 'dev' ? DEV_API_URL : PROD_API_URL);

export const template: AgentTemplate = {
  name: "chat-memory",
  description: "Chat agent with persistent memory and LLM — recommended starting point",
  category: "General",
  variables: [
    { name: "agent_name", required: true, description: "Name of the agent" },
    {
      name: "description",
      required: true,
      description: "Short description of what this agent does",
    },
    {
      name: "system_prompt",
      default: "You are a helpful AI assistant. Be concise and accurate.",
      description: "System prompt for the LLM (auto-generated from description)",
    },
    {
      name: "memory_size",
      default: "20",
      description: "Number of messages to remember per user",
    },
  ],
  dependencies: ["requests", "openai"],
  secrets: ["AGENTVERSE_API_KEY", "AGENTLAUNCH_API_KEY", "AGENT_ADDRESS", "ASI1_API_KEY"],
  code: `#!/usr/bin/env python3
"""
{{agent_name}} — AgentLaunch Agent
Generated by: agentlaunch scaffold {{agent_name}} --type chat-memory

Features:
  - Persistent conversation memory (survives agent restarts)
  - ASI1-mini LLM with domain-specific system prompt
  - Chat Protocol v0.3.0 (discoverable on Agentverse + ASI:One)

Platform constants (source of truth: deployed smart contracts):
  - Deploy fee: 120 FET (read dynamically, can change via multi-sig)
  - Graduation target: 30,000 FET -> auto DEX listing
  - Trading fee: 2% -> 100% to protocol treasury (NO creator fee)
"""

from uagents import Agent, Context, Protocol
from uagents_core.contrib.protocols.chat import (
    ChatAcknowledgement,
    ChatMessage,
    EndSessionContent,
    TextContent,
    chat_protocol_spec,
)
import json
import os
from collections import defaultdict
from datetime import datetime
from typing import Dict, List, Optional
from uuid import uuid4

try:
    from openai import OpenAI
except ImportError:
    OpenAI = None

# ==============================================================================
# CONFIG
# ==============================================================================

AGENTLAUNCH_API = os.environ.get("AGENTLAUNCH_API", "${RESOLVED_API_URL}")
MEMORY_SIZE = {{memory_size}}

AGENT_NAME = "{{agent_name}}"
AGENT_DESCRIPTION = "{{description}}"
AGENT_VERSION = "1.0.0"

SYSTEM_PROMPT = """{{system_prompt}}"""

# ==============================================================================
# PERSISTENT CONVERSATION MEMORY
# ==============================================================================

class ConversationMemory:
    """Per-user conversation history with ctx.storage persistence.

    Memory is stored per-user in ctx.storage so it survives agent restarts.
    Each user's history is stored under key 'mem_{user_id_hash}' to avoid
    key collisions and keep storage organized.
    """

    def __init__(self, max_messages: int = MEMORY_SIZE) -> None:
        self._max = max_messages
        self._cache: Dict[str, List[Dict[str, str]]] = {}

    def _key(self, user_id: str) -> str:
        """Storage key for a user's conversation history."""
        short_id = user_id[-12:]  # Last 12 chars of address for readability
        return f"mem_{short_id}"

    def load(self, ctx: Context, user_id: str) -> None:
        """Load a user's history from persistent storage into cache."""
        if user_id in self._cache:
            return  # Already loaded
        raw = ctx.storage.get(self._key(user_id))
        if raw:
            try:
                self._cache[user_id] = json.loads(raw)[-self._max:]
            except (json.JSONDecodeError, TypeError):
                self._cache[user_id] = []
        else:
            self._cache[user_id] = []

    def save(self, ctx: Context, user_id: str) -> None:
        """Persist a user's history to ctx.storage."""
        history = self._cache.get(user_id, [])
        ctx.storage.set(self._key(user_id), json.dumps(history))

    def add(self, ctx: Context, user_id: str, role: str, content: str) -> None:
        """Add a message and persist."""
        self.load(ctx, user_id)
        self._cache[user_id].append({
            "role": role,
            "content": content,
            "ts": datetime.now().isoformat(),
        })
        if len(self._cache[user_id]) > self._max:
            self._cache[user_id] = self._cache[user_id][-self._max:]
        self.save(ctx, user_id)

    def get(self, ctx: Context, user_id: str) -> List[Dict[str, str]]:
        """Get conversation history for a user."""
        self.load(ctx, user_id)
        return list(self._cache.get(user_id, []))

    def clear(self, ctx: Context, user_id: str) -> None:
        """Clear a user's history from cache and storage."""
        self._cache[user_id] = []
        self.save(ctx, user_id)

    def summary(self, ctx: Context, user_id: str, n: int = 5) -> str:
        """Human-readable summary of recent messages."""
        history = self.get(ctx, user_id)
        if not history:
            return "No conversation history."
        lines = []
        for m in history[-n:]:
            role = m["role"].upper()
            text = m["content"][:120]
            lines.append(f"  [{role}] {text}")
        return f"Last {min(n, len(history))} of {len(history)} messages:\\n" + "\\n".join(lines)

# ==============================================================================
# LLM (ASI1-mini via OpenAI-compatible API)
# ==============================================================================

_llm_client = None

def get_llm_client() -> Optional["OpenAI"]:
    """Get or create OpenAI client configured for ASI1-mini."""
    global _llm_client
    if _llm_client is not None:
        return _llm_client
    api_key = os.environ.get("ASI1_API_KEY", "")
    if not api_key or OpenAI is None:
        return None
    _llm_client = OpenAI(base_url="https://api.asi1.ai/v1", api_key=api_key)
    return _llm_client

def llm_respond(user_text: str, history: List[Dict[str, str]]) -> str:
    """Generate a response using ASI1-mini with conversation history."""
    client = get_llm_client()
    if client is None:
        return (
            "I received your message but LLM is not configured yet. "
            "Please set the ASI1_API_KEY secret on Agentverse."
        )

    # Build messages: system prompt + conversation history + current message
    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    for m in history:
        messages.append({"role": m["role"], "content": m["content"]})
    messages.append({"role": "user", "content": user_text})

    try:
        resp = client.chat.completions.create(
            model="asi1-mini",
            messages=messages,
            max_tokens=1024,
            temperature=0.7,
        )
        return resp.choices[0].message.content.strip()
    except Exception as e:
        return f"Sorry, I encountered an error generating a response: {e}"

# ==============================================================================
# REPLY HELPER
# ==============================================================================

async def reply(ctx: Context, sender: str, text: str, end: bool = False) -> None:
    """Send a chat message, optionally ending the session."""
    content = [TextContent(type="text", text=text)]
    if end:
        content.append(EndSessionContent(type="end-session"))
    try:
        await ctx.send(
            sender,
            ChatMessage(timestamp=datetime.now(), msg_id=uuid4(), content=content),
        )
    except Exception as e:
        ctx.logger.error(f"Failed to send reply: {e}")

# ==============================================================================
# MAIN AGENT
# ==============================================================================

memory = ConversationMemory(max_messages=MEMORY_SIZE)
agent = Agent()
chat_proto = Protocol(spec=chat_protocol_spec)

@chat_proto.on_message(ChatMessage)
async def handle_chat(ctx: Context, sender: str, msg: ChatMessage) -> None:
    # Acknowledge receipt
    try:
        await ctx.send(
            sender,
            ChatAcknowledgement(timestamp=datetime.now(), acknowledged_msg_id=msg.msg_id),
        )
    except Exception as e:
        ctx.logger.error(f"Failed to send ack: {e}")

    # Extract text
    text = " ".join(
        item.text for item in msg.content if isinstance(item, TextContent)
    ).strip()[:2000]

    if not text:
        await reply(ctx, sender, "Please send a text message.", end=True)
        return

    lower = text.lower().strip()

    # --- Built-in commands ---

    if lower in ("help", "?"):
        await reply(
            ctx, sender,
            f"**{AGENT_NAME}** v{AGENT_VERSION}\\n\\n"
            f"{AGENT_DESCRIPTION}\\n\\n"
            f"Commands: help, history, clear",
        )
        return

    if lower == "history":
        summary = memory.summary(ctx, sender)
        await reply(ctx, sender, f"**Conversation History**\\n{summary}")
        return

    if lower == "clear":
        memory.clear(ctx, sender)
        await reply(ctx, sender, "Conversation history cleared.", end=True)
        return

    # --- LLM response with conversation memory ---

    # Get prior history for context (before adding current message)
    history = memory.get(ctx, sender)

    # Store user message
    memory.add(ctx, sender, "user", text)

    # Generate response
    response = llm_respond(text, history)

    # Store assistant response
    memory.add(ctx, sender, "assistant", response[:2000])

    await reply(ctx, sender, response, end=True)

@chat_proto.on_message(ChatAcknowledgement)
async def handle_ack(ctx: Context, sender: str, msg: ChatAcknowledgement) -> None:
    ctx.logger.debug(f"Ack from {sender[:20]} for msg {msg.acknowledged_msg_id}")

agent.include(chat_proto, publish_manifest=True)

if __name__ == "__main__":
    agent.run()
`,
};
