#!/usr/bin/env python3
"""
{{AGENT_NAME}} — AgentLaunch Connect Agent
Generated by: agentlaunch scaffold {{AGENT_NAME}} --type connect

Connects your existing service to Agentverse by forwarding every incoming
chat message to an external HTTP endpoint and returning the response.
All configuration is read from Agentverse secrets so the agent code itself
contains no credentials.

Required secrets (set via Agentverse dashboard or agentverse-cli):
  EXTERNAL_ENDPOINT   The URL to POST each message to (e.g. https://example.com/chat)
  AUTH_HEADER         Optional — name of the auth header  (e.g. Authorization)
  AUTH_SECRET         Optional — value of the auth header (e.g. Bearer sk-...)
  TIMEOUT             Optional — HTTP timeout in seconds  (default: 30)

Request shape sent to EXTERNAL_ENDPOINT:
  POST /chat
  Content-Type: application/json
  {
    "message": "user message text",
    "sender":  "agent1q...",
    "context": {
      "agent_address": "agent1q...",
      "message_id": "uuid"
    }
  }

Response shape from EXTERNAL_ENDPOINT:
  {
    "reply": "response text to send back to sender",
    "outbox": [                          // Optional: messages to send to other agents
      {
        "to": "agent1q...",              // Target agent address
        "message": "Hello other agent!"
      }
    ]
  }

Outbox messages are sent asynchronously. When those agents respond,
their responses arrive as new requests to your endpoint with the
original agent address in the "sender" field.
"""

import asyncio
import os
from datetime import datetime
from typing import Any
from uuid import uuid4

import aiohttp
from uagents import Agent, Context, Protocol
from uagents_core.contrib.protocols.chat import (
    ChatAcknowledgement,
    ChatMessage,
    EndSessionContent,
    TextContent,
    chat_protocol_spec,
)

# ==============================================================================
# CONFIG — all values come from Agentverse secrets
# ==============================================================================

EXTERNAL_ENDPOINT: str = os.environ.get("EXTERNAL_ENDPOINT", "")
AUTH_HEADER: str = os.environ.get("AUTH_HEADER", "")
AUTH_SECRET: str = os.environ.get("AUTH_SECRET", "")
TIMEOUT: int = int(os.environ.get("TIMEOUT", "30"))

# ==============================================================================
# HELPERS
# ==============================================================================


def _build_headers() -> dict:
    """Return HTTP headers for the upstream request, including optional auth."""
    headers = {"Content-Type": "application/json"}
    if AUTH_HEADER and AUTH_SECRET:
        headers[AUTH_HEADER] = AUTH_SECRET
    return headers


async def _forward(
    message: str, sender: str, agent_address: str, message_id: str
) -> dict[str, Any]:
    """POST the message to EXTERNAL_ENDPOINT and return the full response.

    Returns a dict with:
      - reply: str (the text to send back)
      - outbox: list[dict] (optional messages to send to other agents)
    """
    if not EXTERNAL_ENDPOINT:
        return {
            "reply": (
                "Connect agent is not configured yet. "
                "Please set the EXTERNAL_ENDPOINT secret on Agentverse."
            ),
            "outbox": [],
        }

    payload = {
        "message": message,
        "sender": sender,
        "context": {
            "agent_address": agent_address,
            "message_id": message_id,
        },
    }

    try:
        timeout = aiohttp.ClientTimeout(total=TIMEOUT)
        async with aiohttp.ClientSession(timeout=timeout) as session:
            async with session.post(
                EXTERNAL_ENDPOINT,
                json=payload,
                headers=_build_headers(),
            ) as resp:
                if resp.status != 200:
                    return {
                        "reply": (
                            f"Upstream returned HTTP {resp.status}. "
                            "Please check your EXTERNAL_ENDPOINT configuration."
                        ),
                        "outbox": [],
                    }
                data = await resp.json(content_type=None)
                return {
                    "reply": str(data.get("reply", "")).strip()
                    or "Upstream returned an empty reply.",
                    "outbox": data.get("outbox", []),
                }

    except asyncio.TimeoutError:
        return {
            "reply": (
                f"Request timed out after {TIMEOUT}s. "
                "Try increasing the TIMEOUT secret or check your endpoint."
            ),
            "outbox": [],
        }
    except aiohttp.ClientConnectionError as exc:
        return {"reply": f"Could not reach the upstream endpoint: {exc}", "outbox": []}
    except aiohttp.ClientError as exc:
        return {"reply": f"HTTP error while forwarding message: {exc}", "outbox": []}


async def _reply(
    ctx: Context, sender: str, text: str, end: bool = False
) -> None:
    """Send a ChatMessage back to the originating agent."""
    content = [TextContent(type="text", text=text)]
    if end:
        content.append(EndSessionContent(type="end-session"))
    try:
        await ctx.send(
            sender,
            ChatMessage(
                timestamp=datetime.now(),
                msg_id=uuid4(),
                content=content,
            ),
        )
    except Exception as exc:  # noqa: BLE001
        ctx.logger.error(f"Failed to send reply to {sender[:20]}: {exc}")


async def _send_outbox(ctx: Context, outbox: list[dict]) -> None:
    """Send messages from the outbox to other agents.

    Each outbox item should have:
      - to: str (agent address)
      - message: str (text to send)
    """
    for item in outbox:
        to_address = item.get("to", "")
        message_text = item.get("message", "")

        if not to_address or not message_text:
            ctx.logger.warning(f"Skipping invalid outbox item: {item}")
            continue

        # Validate address format
        if not to_address.startswith("agent1q"):
            ctx.logger.warning(f"Invalid agent address in outbox: {to_address[:20]}")
            continue

        try:
            ctx.logger.info(f"Sending outbox message to {to_address[:20]}")
            await ctx.send(
                to_address,
                ChatMessage(
                    timestamp=datetime.now(),
                    msg_id=uuid4(),
                    content=[TextContent(type="text", text=message_text[:4000])],
                ),
            )
        except Exception as exc:  # noqa: BLE001
            ctx.logger.error(f"Failed to send outbox message to {to_address[:20]}: {exc}")


# ==============================================================================
# AGENT
# ==============================================================================

agent = Agent(seed="{{SEED_PHRASE}}")
chat_proto = Protocol(spec=chat_protocol_spec)


@chat_proto.on_message(ChatMessage)
async def handle_chat(ctx: Context, sender: str, msg: ChatMessage) -> None:
    """Handle incoming chat messages.

    1. Acknowledge the message
    2. Forward to external endpoint
    3. Send reply back to sender
    4. Send any outbox messages to other agents
    """
    message_id = str(msg.msg_id)

    # Always acknowledge first so ASI:One does not time out
    try:
        await ctx.send(
            sender,
            ChatAcknowledgement(
                timestamp=datetime.now(),
                acknowledged_msg_id=msg.msg_id,
            ),
        )
    except Exception as exc:  # noqa: BLE001
        ctx.logger.error(f"Failed to send ack to {sender[:20]}: {exc}")

    # Extract text from the message content parts
    text = " ".join(
        item.text for item in msg.content if isinstance(item, TextContent)
    ).strip()[:4000]

    if not text:
        await _reply(ctx, sender, "Please send a text message.", end=True)
        return

    ctx.logger.info(f"Forwarding message from {sender[:20]} to {EXTERNAL_ENDPOINT}")

    # Forward to external endpoint
    response = await _forward(
        message=text,
        sender=sender,
        agent_address=str(ctx.address),
        message_id=message_id,
    )

    # Send reply back to original sender
    reply_text = response.get("reply", "")
    if reply_text:
        await _reply(ctx, sender, reply_text, end=True)

    # Process outbox - send messages to other agents
    outbox = response.get("outbox", [])
    if outbox:
        ctx.logger.info(f"Processing {len(outbox)} outbox message(s)")
        await _send_outbox(ctx, outbox)


@chat_proto.on_message(ChatAcknowledgement)
async def handle_ack(
    ctx: Context, sender: str, msg: ChatAcknowledgement
) -> None:
    ctx.logger.debug(f"Ack from {sender[:20]} for msg {msg.acknowledged_msg_id}")


agent.include(chat_proto, publish_manifest=True)

if __name__ == "__main__":
    agent.run()
