#!/usr/bin/env python3
"""
{{AGENT_NAME}} — AgentLaunch Connect Agent
Generated by: agentlaunch scaffold {{AGENT_NAME}} --type connect

Connects your existing service to Agentverse by forwarding every incoming
chat message to an external HTTP endpoint and returning the response.
All configuration is read from Agentverse secrets so the agent code itself
contains no credentials.

Required secrets (set via Agentverse dashboard or agentverse-cli):
  EXTERNAL_ENDPOINT   The URL to POST each message to (e.g. https://example.com/chat)
  AUTH_HEADER         Optional — name of the auth header  (e.g. Authorization)
  AUTH_SECRET         Optional — value of the auth header (e.g. Bearer sk-...)
  TIMEOUT             Optional — HTTP timeout in seconds  (default: 30)

Expected request shape sent to EXTERNAL_ENDPOINT:
  POST /chat
  Content-Type: application/json
  {
    "message": "user message text",
    "sender":  "agent1q...",
    "context": {"agent_address": "agent1q..."}
  }

Expected response shape from EXTERNAL_ENDPOINT:
  {"reply": "response text"}
"""

import asyncio
import os
from datetime import datetime
from uuid import uuid4

import aiohttp
from uagents import Agent, Context, Protocol
from uagents_core.contrib.protocols.chat import (
    ChatAcknowledgement,
    ChatMessage,
    EndSessionContent,
    TextContent,
    chat_protocol_spec,
)

# ==============================================================================
# CONFIG — all values come from Agentverse secrets
# ==============================================================================

EXTERNAL_ENDPOINT: str = os.environ.get("EXTERNAL_ENDPOINT", "")
AUTH_HEADER: str = os.environ.get("AUTH_HEADER", "")
AUTH_SECRET: str = os.environ.get("AUTH_SECRET", "")
TIMEOUT: int = int(os.environ.get("TIMEOUT", "30"))

# ==============================================================================
# HELPERS
# ==============================================================================


def _build_headers() -> dict:
    """Return HTTP headers for the upstream request, including optional auth."""
    headers = {"Content-Type": "application/json"}
    if AUTH_HEADER and AUTH_SECRET:
        headers[AUTH_HEADER] = AUTH_SECRET
    return headers


async def _forward(message: str, sender: str, agent_address: str) -> str:
    """POST the message to EXTERNAL_ENDPOINT and return the reply text.

    Handles three error categories with distinct user-facing messages:
      - asyncio.TimeoutError   — upstream took too long
      - aiohttp.ClientError    — network / DNS / connection failure
      - Non-200 HTTP status    — upstream returned an error response
    """
    if not EXTERNAL_ENDPOINT:
        return (
            "Connect agent is not configured yet. "
            "Please set the EXTERNAL_ENDPOINT secret on Agentverse."
        )

    payload = {
        "message": message,
        "sender": sender,
        "context": {"agent_address": agent_address},
    }

    try:
        timeout = aiohttp.ClientTimeout(total=TIMEOUT)
        async with aiohttp.ClientSession(timeout=timeout) as session:
            async with session.post(
                EXTERNAL_ENDPOINT,
                json=payload,
                headers=_build_headers(),
            ) as resp:
                if resp.status != 200:
                    return (
                        f"Upstream returned HTTP {resp.status}. "
                        "Please check your EXTERNAL_ENDPOINT configuration."
                    )
                data = await resp.json(content_type=None)
                return str(data.get("reply", "")).strip() or (
                    "Upstream returned an empty reply."
                )

    except asyncio.TimeoutError:
        return (
            f"Request timed out after {TIMEOUT}s. "
            "Try increasing the TIMEOUT secret or check your endpoint."
        )
    except aiohttp.ClientConnectionError as exc:
        return f"Could not reach the upstream endpoint: {exc}"
    except aiohttp.ClientError as exc:
        return f"HTTP error while forwarding message: {exc}"


async def _reply(
    ctx: Context, sender: str, text: str, end: bool = False
) -> None:
    """Send a ChatMessage back to the originating agent."""
    content = [TextContent(type="text", text=text)]
    if end:
        content.append(EndSessionContent(type="end-session"))
    try:
        await ctx.send(
            sender,
            ChatMessage(
                timestamp=datetime.now(),
                msg_id=uuid4(),
                content=content,
            ),
        )
    except Exception as exc:  # noqa: BLE001
        ctx.logger.error(f"Failed to send reply to {sender[:20]}: {exc}")


# ==============================================================================
# AGENT
# ==============================================================================

agent = Agent(seed="{{SEED_PHRASE}}")
chat_proto = Protocol(spec=chat_protocol_spec)


@chat_proto.on_message(ChatMessage)
async def handle_chat(ctx: Context, sender: str, msg: ChatMessage) -> None:
    # Always acknowledge first so ASI:One does not time out
    try:
        await ctx.send(
            sender,
            ChatAcknowledgement(
                timestamp=datetime.now(),
                acknowledged_msg_id=msg.msg_id,
            ),
        )
    except Exception as exc:  # noqa: BLE001
        ctx.logger.error(f"Failed to send ack to {sender[:20]}: {exc}")

    # Extract text from the message content parts
    text = " ".join(
        item.text for item in msg.content if isinstance(item, TextContent)
    ).strip()[:4000]

    if not text:
        await _reply(ctx, sender, "Please send a text message.", end=True)
        return

    ctx.logger.info(f"Forwarding message from {sender[:20]} to {EXTERNAL_ENDPOINT}")

    response = await _forward(
        message=text,
        sender=sender,
        agent_address=str(ctx.address),
    )

    await _reply(ctx, sender, response, end=True)


@chat_proto.on_message(ChatAcknowledgement)
async def handle_ack(
    ctx: Context, sender: str, msg: ChatAcknowledgement
) -> None:
    ctx.logger.debug(f"Ack from {sender[:20]} for msg {msg.acknowledged_msg_id}")


agent.include(chat_proto, publish_manifest=True)

if __name__ == "__main__":
    agent.run()
