/**
 * connect.ts — Connect agent that forwards incoming chat messages to an external HTTP endpoint
 *
 * This template implements the connect pattern: the agent receives a message via
 * Chat Protocol v0.3.0, POSTs it (along with the sender address) to a
 * configurable EXTERNAL_ENDPOINT, and replies with whatever the endpoint
 * returns.  This is useful for connecting your existing agent or service to
 * Agentverse without rebuilding it from scratch.
 */

import type { AgentTemplate } from "../registry.js";

export const template: AgentTemplate = {
  name: "connect",
  description:
    "Connect your agent or service to Agentverse via an external HTTP endpoint",
  category: "Infrastructure",
  variables: [
    {
      name: "AGENT_NAME",
      required: true,
      description: "Display name of the connect agent",
    },
    {
      name: "SEED_PHRASE",
      required: true,
      description: "Seed phrase used to derive the agent's deterministic address",
    },
    {
      name: "EXTERNAL_ENDPOINT",
      required: true,
      description:
        "Full URL of the HTTP endpoint to forward messages to (e.g. https://api.example.com/chat)",
    },
  ],
  dependencies: ["requests"],
  secrets: ["SEED_PHRASE", "EXTERNAL_ENDPOINT"],
  code: `#!/usr/bin/env python3
"""
{{AGENT_NAME}} — AgentLaunch Connect Agent
Generated by: agentlaunch scaffold {{AGENT_NAME}} --type connect

Connects your existing service to Agentverse by forwarding every incoming
Chat Protocol message to an external HTTP endpoint and relaying the response
back to the sender.

Configuration (set as Agentverse secrets):
  SEED_PHRASE        — deterministic agent seed
  EXTERNAL_ENDPOINT  — target URL to forward messages to

The POST body sent to EXTERNAL_ENDPOINT:
  {
    "sender":  "<agentverse address of the caller>",
    "message": "<text content of the chat message>"
  }

Expected response from EXTERNAL_ENDPOINT (JSON):
  { "reply": "<text to send back>" }
  — or any JSON; the full response body is returned if "reply" is absent.
"""

from uagents import Agent, Context, Protocol
from uagents_core.contrib.protocols.chat import (
    ChatAcknowledgement,
    ChatMessage,
    EndSessionContent,
    TextContent,
)
try:
    from uagents_core.contrib.protocols.chat import create_protocol as _create_chat
except ImportError:
    _create_chat = None
try:
    from uagents_core.contrib.protocols.chat import chat_protocol_spec as _chat_spec
except ImportError:
    _chat_spec = None

import json
import os
from datetime import datetime
from uuid import uuid4

import requests as http

# ==============================================================================
# CONFIG
# ==============================================================================

AGENT_NAME = "{{AGENT_NAME}}"
SEED_PHRASE = os.environ.get("SEED_PHRASE", "{{SEED_PHRASE}}")
EXTERNAL_ENDPOINT = os.environ.get("EXTERNAL_ENDPOINT", "{{EXTERNAL_ENDPOINT}}")

REQUEST_TIMEOUT = 30  # seconds

# ==============================================================================
# HELPERS
# ==============================================================================


async def reply(ctx: Context, sender: str, text: str, end: bool = True) -> None:
    """Send a Chat Protocol reply to *sender*."""
    content = [TextContent(type="text", text=text)]
    if end:
        content.append(EndSessionContent(type="end-session"))
    try:
        await ctx.send(
            sender,
            ChatMessage(
                timestamp=datetime.utcnow(), msg_id=uuid4(), content=content
            ),
        )
    except Exception as exc:
        ctx.logger.error(f"[REPLY_ERROR] {exc}")


def forward(sender: str, message: str) -> str:
    """POST the message to EXTERNAL_ENDPOINT and return the reply text."""
    try:
        resp = http.post(
            EXTERNAL_ENDPOINT,
            json={"sender": sender, "message": message},
            timeout=REQUEST_TIMEOUT,
        )
        resp.raise_for_status()
        data = resp.json()
        if isinstance(data, dict) and "reply" in data:
            return str(data["reply"])
        return json.dumps(data)
    except http.exceptions.Timeout:
        return "The upstream service timed out. Please try again."
    except http.exceptions.HTTPError as exc:
        return f"Upstream error: {exc.response.status_code}"
    except Exception as exc:
        return f"Error contacting upstream service: {exc}"


# ==============================================================================
# AGENT
# ==============================================================================

agent = Agent(name=AGENT_NAME, seed=SEED_PHRASE)
chat_proto = _create_chat() if _create_chat else Protocol(spec=_chat_spec)


@chat_proto.on_message(ChatMessage)
async def handle_chat(ctx: Context, sender: str, msg: ChatMessage) -> None:
    # Acknowledge immediately
    try:
        await ctx.send(
            sender,
            ChatAcknowledgement(
                timestamp=datetime.utcnow(), acknowledged_msg_id=msg.msg_id
            ),
        )
    except Exception as exc:
        ctx.logger.error(f"[ACK_ERROR] {exc}")

    text = " ".join(
        item.text for item in msg.content if isinstance(item, TextContent)
    ).strip()

    if not text:
        await reply(ctx, sender, "Empty message — nothing to forward.")
        return

    ctx.logger.info(f"[CONNECT] sender={sender[:20]} len={len(text)} endpoint={EXTERNAL_ENDPOINT}")
    response_text = forward(sender, text)
    await reply(ctx, sender, response_text)


@chat_proto.on_message(ChatAcknowledgement)
async def handle_ack(ctx: Context, sender: str, msg: ChatAcknowledgement) -> None:
    ctx.logger.debug(f"[ACK] from={sender[:20]} msg_id={msg.acknowledged_msg_id}")


agent.include(chat_proto, publish_manifest=True)

if __name__ == "__main__":
    agent.run()
`,
};
