/**
 * consumer-commerce.ts — Consumer-facing agent template with multi-token payments
 *
 * Extends the swarm-starter commerce stack with:
 * - MultiTokenPricingTable (FET + USDC pricing)
 * - InvoiceManager (create/verify/list invoices in ctx.storage)
 * - FiatOnrampHelper (detect "no crypto" → generate card purchase link)
 * - DelegationChecker (verify allowance → auto-pay or fall back to RequestPayment)
 *
 * No custom smart contracts — uses standard ERC-20 approve/transferFrom.
 */

import type { AgentTemplate } from "../registry.js";

const PROD_API_URL = 'https://agent-launch.ai/api';
const DEV_API_URL = 'https://launchpad-backend-dev-1056182620041.us-central1.run.app';
const RESOLVED_API_URL = process.env.AGENT_LAUNCH_API_URL ??
  (process.env.AGENT_LAUNCH_ENV === 'dev' ? DEV_API_URL : PROD_API_URL);

export const template: AgentTemplate = {
  name: "consumer-commerce",
  description: "Consumer-facing agent with multi-token payments, invoices, fiat onramp, and spending delegation",
  category: "Commerce",
  variables: [
    { name: "agent_name", required: true, description: "Name of the agent" },
    { name: "description", required: true, description: "Short description of what this agent does" },
    { name: "service_price_fet", default: "0.01", description: "Service price in FET" },
    { name: "service_price_usdc", default: "0.05", description: "Service price in USDC" },
    { name: "accepted_tokens", default: "FET,USDC", description: "Comma-separated accepted token symbols" },
    { name: "enable_fiat_onramp", default: "true", description: "Enable fiat onramp link generation" },
    { name: "enable_invoices", default: "true", description: "Enable invoice management" },
    { name: "enable_delegation", default: "true", description: "Enable spending delegation (auto-pay)" },
  ],
  dependencies: ["requests", "web3"],
  secrets: [
    "AGENTVERSE_API_KEY",
    "AGENTLAUNCH_API_KEY",
    "WALLET_PRIVATE_KEY",
    "MOONPAY_API_KEY",
  ],
  code: `#!/usr/bin/env python3
"""
{{agent_name}} — AgentLaunch Consumer Commerce Agent
Generated by: agentlaunch scaffold {{agent_name}} --type consumer-commerce

Multi-token payments (FET + USDC), invoices, fiat onramp, spending delegation.
Uses standard ERC-20 patterns — no custom smart contracts.

Platform constants (source of truth: deployed smart contracts):
  - Deploy fee: 120 FET (read dynamically, can change via multi-sig)
  - Graduation target: 30,000 FET -> auto DEX listing
  - Trading fee: 2% -> 100% to protocol treasury (NO creator fee)
"""

from uagents import Agent, Context, Protocol
from uagents_core.contrib.protocols.chat import (
    ChatAcknowledgement,
    ChatMessage,
    EndSessionContent,
    TextContent,
    chat_protocol_spec,
)

import json
import os
from datetime import datetime
from uuid import uuid4

# ==============================================================================
# CONFIG
# ==============================================================================

AGENTLAUNCH_API = os.environ.get("AGENTLAUNCH_API", "${RESOLVED_API_URL}")

BUSINESS = {
    "name": "{{agent_name}}",
    "description": "{{description}}",
    "version": "1.0.0",
}

ACCEPTED_TOKENS = [t.strip() for t in "{{accepted_tokens}}".split(",")]

# ==============================================================================
# MULTI-TOKEN PRICING TABLE
# ==============================================================================

class MultiTokenPricingTable:
    """Service pricing in multiple tokens (FET + USDC)."""

    def __init__(self, ctx: Context):
        self.ctx = ctx

    async def get_prices(self) -> dict:
        """Get current pricing table from storage."""
        raw = self.ctx.storage.get("pricing_table")
        if raw:
            return json.loads(raw)
        # Default pricing
        return {
            "default": {
                "FET": "{{service_price_fet}}",
                "USDC": "{{service_price_usdc}}",
            }
        }

    async def set_price(self, service: str, token: str, price: str):
        """Set price for a service in a specific token."""
        prices = await self.get_prices()
        if service not in prices:
            prices[service] = {}
        prices[service][token] = price
        self.ctx.storage.set("pricing_table", json.dumps(prices))

    async def format_prices(self, service: str = "default") -> str:
        """Format prices for display."""
        prices = await self.get_prices()
        svc_prices = prices.get(service, prices.get("default", {}))
        lines = []
        for token, price in svc_prices.items():
            if token in ACCEPTED_TOKENS:
                lines.append(f"  {price} {token}")
        return "\\n".join(lines) if lines else "  Free"

# ==============================================================================
# INVOICE MANAGER
# ==============================================================================

class InvoiceManager:
    """Create, verify, and list invoices in ctx.storage."""

    def __init__(self, ctx: Context):
        self.ctx = ctx

    async def create(self, payer: str, service: str, amount: str, token: str = "FET") -> dict:
        """Create a new invoice."""
        invoice_id = f"inv_{uuid4().hex[:8]}"
        invoice = {
            "id": invoice_id,
            "issuer": str(self.ctx.address),
            "payer": payer,
            "service": service,
            "amount": amount,
            "token": token,
            "status": "pending",
            "created_at": datetime.now().isoformat(),
            "updated_at": datetime.now().isoformat(),
        }
        self.ctx.storage.set(f"invoice_{invoice_id}", json.dumps(invoice))

        # Update index
        index_raw = self.ctx.storage.get("invoice_index")
        index = json.loads(index_raw) if index_raw else []
        index.append(invoice_id)
        self.ctx.storage.set("invoice_index", json.dumps(index))

        return invoice

    async def get(self, invoice_id: str) -> dict | None:
        """Get an invoice by ID."""
        raw = self.ctx.storage.get(f"invoice_{invoice_id}")
        return json.loads(raw) if raw else None

    async def list_invoices(self, status: str = None) -> list:
        """List all invoices, optionally filtered by status."""
        index_raw = self.ctx.storage.get("invoice_index")
        if not index_raw:
            return []
        index = json.loads(index_raw)
        invoices = []
        for inv_id in index:
            inv = await self.get(inv_id)
            if inv and (status is None or inv.get("status") == status):
                invoices.append(inv)
        return invoices

    async def mark_paid(self, invoice_id: str, tx_hash: str) -> dict | None:
        """Mark an invoice as paid."""
        inv = await self.get(invoice_id)
        if not inv:
            return None
        inv["status"] = "paid"
        inv["tx_hash"] = tx_hash
        inv["updated_at"] = datetime.now().isoformat()
        self.ctx.storage.set(f"invoice_{invoice_id}", json.dumps(inv))
        return inv

# ==============================================================================
# FIAT ONRAMP HELPER
# ==============================================================================

class FiatOnrampHelper:
    """Generate fiat-to-crypto purchase links for users without crypto."""

    PROVIDERS = {
        "moonpay": "https://buy.moonpay.com",
        "transak": "https://global.transak.com",
    }

    CRYPTO_CODES = {
        "FET": {"moonpay": "fet_bsc", "transak": "FET"},
        "USDC": {"moonpay": "usdc_bsc", "transak": "USDC"},
    }

    def __init__(self, ctx: Context):
        self.ctx = ctx
        self.enabled = "{{enable_fiat_onramp}}" == "true"

    def generate_link(
        self,
        wallet_address: str,
        fiat_amount: str = "50",
        fiat_currency: str = "USD",
        crypto_token: str = "FET",
        provider: str = "moonpay",
    ) -> str | None:
        """Generate a fiat onramp URL."""
        if not self.enabled:
            return None

        codes = self.CRYPTO_CODES.get(crypto_token.upper())
        if not codes:
            return None

        base_url = self.PROVIDERS.get(provider)
        if not base_url:
            return None

        api_key = os.environ.get("MOONPAY_API_KEY", "")

        if provider == "moonpay":
            return (
                f"{base_url}?"
                f"apiKey={api_key}&"
                f"currencyCode={codes['moonpay']}&"
                f"baseCurrencyCode={fiat_currency.lower()}&"
                f"baseCurrencyAmount={fiat_amount}&"
                f"walletAddress={wallet_address}"
            )
        else:
            return (
                f"{base_url}?"
                f"apiKey={api_key}&"
                f"cryptoCurrencyCode={codes['transak']}&"
                f"fiatCurrency={fiat_currency.upper()}&"
                f"fiatAmount={fiat_amount}&"
                f"walletAddress={wallet_address}&"
                f"network=bsc"
            )

# ==============================================================================
# DELEGATION CHECKER
# ==============================================================================

class DelegationChecker:
    """Check ERC-20 allowances for auto-pay from delegated spending limits."""

    def __init__(self, ctx: Context):
        self.ctx = ctx
        self.enabled = "{{enable_delegation}}" == "true"

    async def check_delegation(self, owner: str, token_address: str) -> str:
        """Check allowance on-chain. Returns remaining allowance as string."""
        if not self.enabled:
            return "0"

        # Store delegation status in ctx.storage for tracking
        key = f"delegation_{owner}_{token_address[:8]}"
        raw = self.ctx.storage.get(key)
        if raw:
            return json.loads(raw).get("remaining", "0")
        return "0"

    async def record_delegation(self, owner: str, token_address: str, amount: str):
        """Record a delegation grant in storage."""
        key = f"delegation_{owner}_{token_address[:8]}"
        self.ctx.storage.set(key, json.dumps({
            "owner": owner,
            "token_address": token_address,
            "remaining": amount,
            "updated_at": datetime.now().isoformat(),
        }))

# ==============================================================================
# REVENUE TRACKER
# ==============================================================================

class RevenueTracker:
    """Track income and expenses by token."""

    def __init__(self, ctx: Context):
        self.ctx = ctx

    async def record_income(self, amount: str, token: str, service: str, payer: str):
        """Record an income event."""
        raw = self.ctx.storage.get("revenue_summary") or "{}"
        summary = json.loads(raw)

        by_token = summary.get("by_token", {})
        if token not in by_token:
            by_token[token] = {"income": 0.0, "expenses": 0.0}
        by_token[token]["income"] += float(amount)
        summary["by_token"] = by_token
        summary["total_income"] = summary.get("total_income", 0.0) + float(amount)
        summary["transaction_count"] = summary.get("transaction_count", 0) + 1
        summary["last_updated"] = datetime.now().isoformat()

        self.ctx.storage.set("revenue_summary", json.dumps(summary))

    async def get_summary(self) -> dict:
        """Get revenue summary."""
        raw = self.ctx.storage.get("revenue_summary") or "{}"
        return json.loads(raw)

# ==============================================================================
# AGENT SETUP
# ==============================================================================

agent = Agent()
chat_proto = Protocol(spec=chat_protocol_spec)

# ==============================================================================
# CHAT HANDLER — COMMERCE FLOW
# ==============================================================================

@chat_proto.on_message(ChatMessage)
async def handle_message(ctx: Context, sender: str, msg: ChatMessage):
    ctx.logger.info(f"Message from {sender}")
    text = msg.content[0].text.strip() if msg.content else ""
    lower = text.lower()

    pricing = MultiTokenPricingTable(ctx)
    invoices = InvoiceManager(ctx)
    fiat = FiatOnrampHelper(ctx)
    revenue = RevenueTracker(ctx)

    # --- Commands ---

    if lower in ("help", "/help"):
        prices = await pricing.format_prices()
        response = (
            f"**{BUSINESS['name']}** — {BUSINESS['description']}\\n\\n"
            f"**Pricing:**\\n{prices}\\n\\n"
            f"**Commands:**\\n"
            f"  \`help\` — Show this message\\n"
            f"  \`prices\` — View pricing in all tokens\\n"
            f"  \`invoice <service>\` — Create an invoice\\n"
            f"  \`buy-crypto\` — Get a link to buy crypto with a card\\n"
            f"  \`revenue\` — View earnings\\n"
            f"  \`status\` — Service status\\n\\n"
            f"**Accepted tokens:** {', '.join(ACCEPTED_TOKENS)}"
        )

    elif lower == "prices":
        prices = await pricing.format_prices()
        response = f"**Current Pricing:**\\n{prices}\\n\\n**Accepted:** {', '.join(ACCEPTED_TOKENS)}"

    elif lower.startswith("invoice"):
        parts = text.split(maxsplit=1)
        service = parts[1] if len(parts) > 1 else "default"
        inv = await invoices.create(sender, service, "{{service_price_fet}}", "FET")
        response = (
            f"**Invoice Created**\\n"
            f"  ID: {inv['id']}\\n"
            f"  Service: {inv['service']}\\n"
            f"  Amount: {inv['amount']} {inv['token']}\\n"
            f"  Status: {inv['status']}"
        )

    elif lower in ("buy-crypto", "buy crypto", "no crypto", "get crypto"):
        link = fiat.generate_link(sender, "50", "USD", "FET")
        if link:
            response = (
                f"**Buy crypto with your card:**\\n"
                f"[Purchase FET]({link})\\n\\n"
                f"You\\'ll receive FET in your wallet within minutes."
            )
        else:
            response = "Fiat onramp is not enabled for this agent."

    elif lower == "revenue":
        summary = await revenue.get_summary()
        total = summary.get("total_income", 0)
        txns = summary.get("transaction_count", 0)
        by_token = summary.get("by_token", {})
        token_lines = "\\n".join(
            f"  {t}: {d.get('income', 0):.4f} income, {d.get('expenses', 0):.4f} expenses"
            for t, d in by_token.items()
        ) if by_token else "  No revenue yet"
        response = (
            f"**Revenue Summary**\\n"
            f"  Total income: {total:.4f}\\n"
            f"  Transactions: {txns}\\n\\n"
            f"**By Token:**\\n{token_lines}"
        )

    elif lower == "status":
        inv_list = await invoices.list_invoices("pending")
        response = (
            f"**{BUSINESS['name']}** v{BUSINESS['version']}\\n"
            f"  Accepted tokens: {', '.join(ACCEPTED_TOKENS)}\\n"
            f"  Pending invoices: {len(inv_list)}\\n"
            f"  Delegation: {'enabled' if '{{enable_delegation}}' == 'true' else 'disabled'}\\n"
            f"  Fiat onramp: {'enabled' if '{{enable_fiat_onramp}}' == 'true' else 'disabled'}"
        )

    else:
        # === YOUR COMMERCE LOGIC ===
        # This is where you add your custom service logic.
        # After fulfilling a service, record revenue:
        #   await revenue.record_income("0.01", "FET", "my_service", sender)
        prices = await pricing.format_prices()
        response = (
            f"Welcome to **{BUSINESS['name']}**!\\n\\n"
            f"{BUSINESS['description']}\\n\\n"
            f"**Pricing:**\\n{prices}\\n\\n"
            f"Type \`help\` for commands, or \`invoice <service>\` to get started."
        )

    await ctx.send(sender, ChatMessage(
        timestamp=datetime.now(),
        msg_id=msg.msg_id,
        content=[TextContent(text=response)],
    ))

    await ctx.send(sender, ChatMessage(
        timestamp=datetime.now(),
        msg_id=msg.msg_id,
        content=[EndSessionContent()],
    ))


@chat_proto.on_message(ChatAcknowledgement)
async def handle_ack(ctx: Context, sender: str, msg: ChatAcknowledgement):
    ctx.logger.info(f"Ack from {sender}: {msg.acknowledged_msg_id}")


agent.include(chat_proto, publish_manifest=True)

if __name__ == "__main__":
    agent.run()
`,
};
