/**
 * price-monitor.ts — Monitors token prices and sends alerts when thresholds are crossed
 *
 * Platform constants (source of truth: deployed smart contracts):
 *   - Deploy fee: 120 FET (read dynamically, can change via multi-sig)
 *   - Graduation target: 30,000 FET -> auto DEX listing
 *   - Trading fee: 2% -> 100% to protocol treasury (NO creator fee)
 */

import type { AgentTemplate } from "../registry.js";

// Environment-based URL resolution
const DEV_API_URL = 'https://launchpad-backend-dev-1056182620041.us-central1.run.app';
const PROD_API_URL = 'https://agent-launch.ai/api';
const RESOLVED_API_URL = process.env.AGENT_LAUNCH_API_URL ??
  (process.env.AGENT_LAUNCH_ENV === 'production' ? PROD_API_URL : DEV_API_URL);

export const template: AgentTemplate = {
  name: "price-monitor",
  description:
    "Monitors token prices and sends alerts when thresholds are crossed",
  category: "AI/ML",
  variables: [
    { name: "agent_name", required: true, description: "Name of the agent" },
    {
      name: "description",
      default: "Monitors token prices and sends alerts when thresholds are crossed",
      description: "Short description of what this agent does",
    },
    {
      name: "token_address",
      required: false,
      description: "Default token address to monitor (can be overridden per user)",
    },
    {
      name: "alert_threshold",
      default: "5",
      description: "Price change percentage that triggers an alert",
    },
    {
      name: "poll_interval_seconds",
      default: "60",
      description: "How often to poll prices (seconds)",
    },
    {
      name: "rate_limit_per_minute",
      default: "20",
      description: "Max requests per user per minute",
    },
    {
      name: "free_requests_per_day",
      default: "10",
      description: "Free tier daily request quota",
    },
    {
      name: "premium_token_threshold",
      default: "1000",
      description: "Token balance required for premium tier",
    },
  ],
  dependencies: ["requests"],
  secrets: ["AGENTVERSE_API_KEY", "AGENTLAUNCH_API_KEY", "AGENT_ADDRESS", "AGENT_OWNER_ADDRESS"],
  code: `#!/usr/bin/env python3
"""
{{agent_name}} — AgentLaunch Price Monitor Agent
Generated by: agentlaunch scaffold {{agent_name}} --type price-monitor

Watches token prices on agent-launch.ai and sends alerts when the price
moves by more than {{alert_threshold}}% within the polling window.

Platform constants (source of truth: deployed smart contracts):
  - Deploy fee: 120 FET (read dynamically, can change via multi-sig)
  - Graduation target: 30,000 FET -> auto DEX listing
  - Trading fee: 2% -> 100% to protocol treasury (NO creator fee)
"""

from uagents import Agent, Context, Protocol
from uagents_core.contrib.protocols.chat import (
    ChatAcknowledgement,
    ChatMessage,
    EndSessionContent,
    TextContent,
    chat_protocol_spec,
)

import json
import os
import time
from collections import defaultdict
from datetime import datetime
from typing import Any, Dict, List, Optional
from uuid import uuid4

import requests

# ==============================================================================
# API CONFIG — Override via environment variables, never hardcode
# ==============================================================================

AGENTLAUNCH_API = os.environ.get("AGENTLAUNCH_API", "${RESOLVED_API_URL}")

# ==============================================================================
# BUSINESS CONFIG
# ==============================================================================

OWNER_ADDRESS = os.environ.get("AGENT_OWNER_ADDRESS", "")

BUSINESS = {
    "name": "{{agent_name}}",
    "description": "{{description}}",
    "version": "1.0.0",
    "default_token_address": "{{token_address}}",
    "alert_threshold_pct": float("{{alert_threshold}}"),
    "poll_interval_seconds": int("{{poll_interval_seconds}}"),
    "free_requests_per_day": {{free_requests_per_day}},
    "premium_token_threshold": {{premium_token_threshold}},
    "rate_limit_per_minute": {{rate_limit_per_minute}},
    "max_input_length": 5000,
}


# ==============================================================================
# LAYER 1: FOUNDATION
# ==============================================================================


class Logger:
    """Structured logging with audit trail."""

    @staticmethod
    def info(ctx: Context, event: str, data: Optional[Dict] = None) -> None:
        ctx.logger.info(f"[{event}] {json.dumps(data or {})}")

    @staticmethod
    def audit(ctx: Context, user: str, action: str) -> None:
        ctx.logger.info(
            f"[AUDIT] user={user[:20]} action={action} "
            f"ts={datetime.utcnow().isoformat()}"
        )

    @staticmethod
    def error(ctx: Context, event: str, error: str) -> None:
        ctx.logger.error(f"[{event}] {error}")


# ==============================================================================
# LAYER 2: SECURITY
# ==============================================================================


class Security:
    """Rate limiting and input validation."""

    def __init__(self) -> None:
        self._requests: Dict[str, List[float]] = defaultdict(list)
        self._check_count: int = 0

    def check(self, ctx: Context, user_id: str, message: str) -> tuple:
        now = time.time()

        self._requests[user_id] = [
            t for t in self._requests[user_id] if now - t < 60
        ]
        if len(self._requests[user_id]) >= BUSINESS["rate_limit_per_minute"]:
            return None, "Rate limit exceeded. Please wait a moment."
        self._requests[user_id].append(now)

        self._check_count += 1
        if self._check_count % 100 == 0:
            stale = [
                k
                for k, v in self._requests.items()
                if not v or (now - max(v)) > 300
            ]
            for k in stale:
                del self._requests[k]

        if not message or not message.strip():
            return None, "Empty message."
        if len(message) > BUSINESS["max_input_length"]:
            return None, f"Message too long (max {BUSINESS['max_input_length']} chars)."

        return message.strip(), None


# ==============================================================================
# LAYER 3: STABILITY
# ==============================================================================


class Health:
    """Track uptime and error rate."""

    def __init__(self) -> None:
        self._start: datetime = datetime.utcnow()
        self._requests: int = 0
        self._errors: int = 0

    def record(self, success: bool) -> None:
        self._requests += 1
        if not success:
            self._errors += 1

    def status(self) -> Dict[str, Any]:
        uptime = (datetime.utcnow() - self._start).total_seconds()
        error_rate = (self._errors / self._requests * 100) if self._requests else 0
        return {
            "status": "healthy" if error_rate < 10 else "degraded",
            "uptime_seconds": int(uptime),
            "requests": self._requests,
            "error_rate": f"{error_rate:.1f}%",
        }


# ==============================================================================
# LAYER 4: SPEED
# ==============================================================================


class Cache:
    """In-memory TTL cache."""

    def __init__(self, max_size: int = 1000) -> None:
        self._data: Dict[str, tuple] = {}
        self._max_size: int = max_size

    def get(self, key: str) -> Any:
        if key in self._data:
            value, expires = self._data[key]
            if expires > time.time():
                return value
            del self._data[key]
        return None

    def set(self, key: str, value: Any, ttl: int = 300) -> None:
        if len(self._data) >= self._max_size:
            now = time.time()
            expired = [k for k, (_, exp) in self._data.items() if exp <= now]
            for k in expired:
                del self._data[k]
            if len(self._data) >= self._max_size:
                to_drop = sorted(self._data.items(), key=lambda x: x[1][1])[
                    : self._max_size // 10
                ]
                for k, _ in to_drop:
                    del self._data[k]
        self._data[key] = (value, time.time() + ttl)


# ==============================================================================
# LAYER 5: REVENUE
# ==============================================================================


class Revenue:
    """Token-gated access and daily usage quotas."""

    def __init__(self, cache: Cache) -> None:
        self._cache = cache
        self._usage: Dict[str, List[str]] = defaultdict(list)

    def get_tier(self, user_address: str) -> str:
        cached = self._cache.get(f"tier:{user_address}")
        if cached is not None:
            return cached
        try:
            r = requests.get(
                f"{AGENTLAUNCH_API}/agents/token/{user_address}", timeout=5
            )
            if r.status_code == 200:
                data = r.json()
                balance = data.get("balance", 0)
                tier = (
                    "premium"
                    if balance >= BUSINESS["premium_token_threshold"]
                    else "free"
                )
                self._cache.set(f"tier:{user_address}", tier, ttl=300)
                return tier
        except Exception:
            pass
        return "free"

    def check_quota(self, user_id: str, tier: str) -> tuple:
        today = datetime.utcnow().date().isoformat()
        self._usage[user_id] = [
            t for t in self._usage[user_id] if t.startswith(today)
        ]
        today_usage = len(self._usage[user_id])
        limit = 1000 if tier == "premium" else BUSINESS["free_requests_per_day"]
        if today_usage >= limit:
            if tier == "free":
                return False, (
                    f"Free limit reached ({limit}/day). "
                    f"Hold {BUSINESS['premium_token_threshold']} tokens for premium!"
                )
            return False, f"Daily limit reached ({limit}/day)."
        self._usage[user_id].append(datetime.utcnow().isoformat())
        return True, None


# ==============================================================================
# AGENTLAUNCH INTEGRATION
# ==============================================================================


class AgentLaunch:
    """Create and manage tokens on AgentLaunch."""

    @staticmethod
    def tokenize() -> Dict:
        agent_address = os.environ.get("AGENT_ADDRESS")
        if not agent_address:
            return {"error": "AGENT_ADDRESS env var not set."}
        try:
            r = requests.post(
                f"{AGENTLAUNCH_API}/agents/tokenize",
                headers={
                    "X-API-Key": os.environ.get("AGENTLAUNCH_API_KEY", ""),
                    "Content-Type": "application/json",
                },
                json={
                    "agentAddress": agent_address,
                    "name": BUSINESS["name"],
                    "description": BUSINESS["description"],
                },
                timeout=30,
            )
            return r.json() if r.status_code in [200, 201] else {"error": r.text}
        except Exception as e:
            return {"error": str(e)}


# ==============================================================================
# PRICE MONITOR BUSINESS LOGIC
# ==============================================================================


class PriceMonitorBusiness:
    """
    Fetches token price from agent-launch.ai/api, compares with last known
    price, and reports whether the threshold has been breached.

    Note: Trading fee is 2% -> 100% to protocol treasury (no creator fee).
    """

    def __init__(self) -> None:
        self._price_history: Dict[str, List[Dict]] = defaultdict(list)

    def fetch_price(self, token_address: str) -> Optional[float]:
        """Fetch the current token price from the AgentLaunch API."""
        try:
            r = requests.get(
                f"{AGENTLAUNCH_API}/agents/token/{token_address}", timeout=10
            )
            if r.status_code == 200:
                data = r.json()
                # Price may be in data.price or data.data.price depending on API version
                price = (
                    data.get("price")
                    or (data.get("data") or {}).get("price")
                )
                return float(price) if price is not None else None
        except Exception:
            pass
        return None

    def check_alert(self, token_address: str, current_price: float) -> Optional[str]:
        """Compare current price to recent history; return alert string if threshold crossed."""
        history = self._price_history[token_address]
        if not history:
            return None
        baseline = history[0]["price"]
        if baseline == 0:
            return None
        change_pct = ((current_price - baseline) / baseline) * 100
        threshold = BUSINESS["alert_threshold_pct"]
        if abs(change_pct) >= threshold:
            direction = "UP" if change_pct > 0 else "DOWN"
            return (
                f"ALERT [{token_address[:10]}...] price {direction} "
                f"{change_pct:+.2f}% (baseline: {baseline:.6f} FET, "
                f"current: {current_price:.6f} FET)"
            )
        return None

    def record_price(self, token_address: str, price: float) -> None:
        history = self._price_history[token_address]
        history.append({"price": price, "ts": datetime.utcnow().isoformat()})
        # Keep last 100 data points
        if len(history) > 100:
            self._price_history[token_address] = history[-100:]

    async def handle(self, ctx: Context, user_id: str, message: str, tier: str) -> str:
        lower = message.lower()

        # Parse "watch <address>" or "monitor <address>"
        if lower.startswith("watch ") or lower.startswith("monitor "):
            parts = message.split()
            if len(parts) >= 2:
                token_address = parts[1].strip()
                price = self.fetch_price(token_address)
                if price is None:
                    return f"Could not fetch price for {token_address}. Check the address."
                self.record_price(token_address, price)
                return (
                    f"Now monitoring {token_address[:12]}...\\n"
                    f"Current price: {price:.6f} FET\\n"
                    f"Alert threshold: {BUSINESS['alert_threshold_pct']}% change"
                )

        # "check <address>" — check current price and alert status
        if lower.startswith("check "):
            parts = message.split()
            if len(parts) >= 2:
                token_address = parts[1].strip()
                price = self.fetch_price(token_address)
                if price is None:
                    return f"Could not fetch price for {token_address}."
                self.record_price(token_address, price)
                alert = self.check_alert(token_address, price)
                status = alert if alert else f"No alert. Price: {price:.6f} FET"
                return status

        # "price <address>" — quick price lookup
        if lower.startswith("price "):
            parts = message.split()
            if len(parts) >= 2:
                token_address = parts[1].strip()
                price = self.fetch_price(token_address)
                if price is None:
                    return f"Could not fetch price for {token_address}."
                return f"Price of {token_address[:12]}...: {price:.6f} FET"

        # Default: check the configured default token
        default_addr = BUSINESS["default_token_address"]
        if default_addr:
            price = self.fetch_price(default_addr)
            if price is not None:
                self.record_price(default_addr, price)
                alert = self.check_alert(default_addr, price)
                info = alert if alert else f"Price: {price:.6f} FET (no alert)"
                return (
                    f"Default token ({default_addr[:12]}...) — {info}\\n\\n"
                    f"Commands: watch <addr>, check <addr>, price <addr>"
                )

        return (
            f"Welcome to {BUSINESS['name']}!\\n\\n"
            f"Commands:\\n"
            f"  watch <token_address>   — start monitoring a token\\n"
            f"  check <token_address>   — check current price + alert status\\n"
            f"  price <token_address>   — quick price lookup\\n\\n"
            f"Alert threshold: {BUSINESS['alert_threshold_pct']}% price change"
        )


# ==============================================================================
# REPLY HELPER
# ==============================================================================


async def reply(ctx: Context, sender: str, text: str, end: bool = False) -> None:
    content = [TextContent(type="text", text=text)]
    if end:
        content.append(EndSessionContent(type="end-session"))
    try:
        await ctx.send(
            sender,
            ChatMessage(timestamp=datetime.utcnow(), msg_id=uuid4(), content=content),
        )
    except Exception as e:
        ctx.logger.error(f"Failed to send reply to {sender[:20]}: {e}")


# ==============================================================================
# MAIN AGENT
# ==============================================================================

cache = Cache(max_size=1000)
security = Security()
health = Health()
revenue = Revenue(cache)
business = PriceMonitorBusiness()

agent = Agent()
chat_proto = Protocol(spec=chat_protocol_spec)


@chat_proto.on_message(ChatMessage)
async def handle_chat(ctx: Context, sender: str, msg: ChatMessage) -> None:
    try:
        await ctx.send(
            sender,
            ChatAcknowledgement(
                timestamp=datetime.utcnow(), acknowledged_msg_id=msg.msg_id
            ),
        )
    except Exception as e:
        ctx.logger.error(f"Failed to send ack to {sender[:20]}: {e}")

    text = " ".join(
        item.text for item in msg.content if isinstance(item, TextContent)
    ).strip()
    text = text[: BUSINESS["max_input_length"]]

    clean, error = security.check(ctx, sender, text)
    if error:
        health.record(False)
        await reply(ctx, sender, error, end=True)
        return

    Logger.audit(ctx, sender, "request")

    lower = clean.lower()

    if lower in ("help", "?"):
        tier = revenue.get_tier(sender)
        await reply(
            ctx,
            sender,
            f"**{BUSINESS['name']}** v{BUSINESS['version']}\\n\\n"
            f"{BUSINESS['description']}\\n\\n"
            f"Your tier: {tier.upper()}\\n\\n"
            f"Commands: help, status, tokenize, watch <addr>, check <addr>, price <addr>",
        )
        return

    if lower == "status":
        s = health.status()
        await reply(
            ctx,
            sender,
            f"Status: {s['status']} | Uptime: {s['uptime_seconds']}s | "
            f"Requests: {s['requests']} | Error rate: {s['error_rate']}",
        )
        return

    if "tokenize" in lower:
        if OWNER_ADDRESS and sender != OWNER_ADDRESS:
            await reply(ctx, sender, "Only the agent owner can trigger tokenization.", end=True)
            return
        result = AgentLaunch.tokenize()
        link = result.get("data", {}).get("handoff_link") or result.get("handoff_link")
        await reply(
            ctx,
            sender,
            f"Token created! Deploy here: {link}" if link else f"Result: {json.dumps(result)}",
            end=True,
        )
        return

    tier = revenue.get_tier(sender)
    allowed, quota_error = revenue.check_quota(sender, tier)
    if not allowed:
        health.record(False)
        await reply(ctx, sender, quota_error, end=True)
        return

    try:
        response = await business.handle(ctx, sender, clean, tier)
        health.record(True)
    except Exception as e:
        health.record(False)
        Logger.error(ctx, "business_handle", str(e))
        response = "Something went wrong. Please try again."

    await reply(ctx, sender, response, end=True)


@chat_proto.on_message(ChatAcknowledgement)
async def handle_ack(ctx: Context, sender: str, msg: ChatAcknowledgement) -> None:
    ctx.logger.debug(f"Ack from {sender[:20]} for msg {msg.acknowledged_msg_id}")


@agent.on_interval(period=3600)
async def periodic_health(ctx: Context) -> None:
    ctx.logger.info(f"[HEALTH] {json.dumps(health.status())}")


agent.include(chat_proto, publish_manifest=True)

if __name__ == "__main__":
    agent.run()
`,
};
