/**
 * trading-bot.ts — Generates buy/sell signals based on price momentum
 *
 * Platform constants (source of truth: deployed smart contracts):
 *   - Deploy fee: 120 FET (read dynamically, can change via multi-sig)
 *   - Graduation target: 30,000 FET -> auto DEX listing
 *   - Trading fee: 2% -> 100% to protocol treasury (NO creator fee)
 */

import type { AgentTemplate } from "../registry.js";

// Environment-based URL resolution
const DEV_API_URL = 'https://launchpad-backend-dev-1056182620041.us-central1.run.app';
const PROD_API_URL = 'https://agent-launch.ai/api';
const RESOLVED_API_URL = process.env.AGENT_LAUNCH_API_URL ??
  (process.env.AGENT_LAUNCH_ENV === 'production' ? PROD_API_URL : DEV_API_URL);

export const template: AgentTemplate = {
  name: "trading-bot",
  description:
    "Generates buy/sell signals for tokens based on price momentum and moving averages",
  category: "Finance",
  variables: [
    { name: "agent_name", required: true, description: "Name of the agent" },
    {
      name: "description",
      default: "Generates buy/sell signals based on price momentum and moving averages",
      description: "Short description of what this agent does",
    },
    {
      name: "signal_window",
      default: "10",
      description: "Number of price data points used to compute moving average",
    },
    {
      name: "buy_threshold",
      default: "3",
      description: "Percentage above moving average to trigger a BUY signal",
    },
    {
      name: "sell_threshold",
      default: "3",
      description: "Percentage below moving average to trigger a SELL signal",
    },
    {
      name: "rate_limit_per_minute",
      default: "20",
      description: "Max requests per user per minute",
    },
    {
      name: "free_requests_per_day",
      default: "10",
      description: "Free tier daily request quota",
    },
    {
      name: "premium_token_threshold",
      default: "1000",
      description: "Token balance required for premium tier",
    },
  ],
  dependencies: ["requests"],
  secrets: ["AGENTVERSE_API_KEY", "AGENTLAUNCH_API_KEY", "AGENT_ADDRESS", "AGENT_OWNER_ADDRESS"],
  code: `#!/usr/bin/env python3
"""
{{agent_name}} — AgentLaunch Trading Signal Agent
Generated by: agentlaunch scaffold {{agent_name}} --type trading-bot

Generates buy/sell signals using a simple moving-average crossover strategy.
Signals are advisory only — this agent does NOT execute trades.

Platform constants (source of truth: deployed smart contracts):
  - Deploy fee: 120 FET (read dynamically, can change via multi-sig)
  - Graduation target: 30,000 FET -> auto DEX listing
  - Trading fee: 2% -> 100% to protocol treasury (NO creator fee)

DISCLAIMER: This agent provides informational signals only, not financial advice.
"""

from uagents import Agent, Context, Protocol
from uagents_core.contrib.protocols.chat import (
    ChatAcknowledgement,
    ChatMessage,
    EndSessionContent,
    TextContent,
    chat_protocol_spec,
)

import json
import os
import time
from collections import defaultdict
from datetime import datetime
from typing import Any, Dict, List, Optional
from uuid import uuid4

import requests

# ==============================================================================
# API CONFIG — Override via environment variables, never hardcode
# ==============================================================================

AGENTLAUNCH_API = os.environ.get("AGENTLAUNCH_API", "${RESOLVED_API_URL}")

# ==============================================================================
# BUSINESS CONFIG
# ==============================================================================

OWNER_ADDRESS = os.environ.get("AGENT_OWNER_ADDRESS", "")

BUSINESS = {
    "name": "{{agent_name}}",
    "description": "{{description}}",
    "version": "1.0.0",
    "signal_window": int("{{signal_window}}"),
    "buy_threshold_pct": float("{{buy_threshold}}"),
    "sell_threshold_pct": float("{{sell_threshold}}"),
    "free_requests_per_day": {{free_requests_per_day}},
    "premium_token_threshold": {{premium_token_threshold}},
    "rate_limit_per_minute": {{rate_limit_per_minute}},
    "max_input_length": 5000,
}


# ==============================================================================
# LAYER 1: FOUNDATION
# ==============================================================================


class Logger:
    """Structured logging with audit trail."""

    @staticmethod
    def info(ctx: Context, event: str, data: Optional[Dict] = None) -> None:
        ctx.logger.info(f"[{event}] {json.dumps(data or {})}")

    @staticmethod
    def audit(ctx: Context, user: str, action: str) -> None:
        ctx.logger.info(
            f"[AUDIT] user={user[:20]} action={action} "
            f"ts={datetime.utcnow().isoformat()}"
        )

    @staticmethod
    def error(ctx: Context, event: str, error: str) -> None:
        ctx.logger.error(f"[{event}] {error}")


# ==============================================================================
# LAYER 2: SECURITY
# ==============================================================================


class Security:
    """Rate limiting and input validation."""

    def __init__(self) -> None:
        self._requests: Dict[str, List[float]] = defaultdict(list)
        self._check_count: int = 0

    def check(self, ctx: Context, user_id: str, message: str) -> tuple:
        now = time.time()

        self._requests[user_id] = [
            t for t in self._requests[user_id] if now - t < 60
        ]
        if len(self._requests[user_id]) >= BUSINESS["rate_limit_per_minute"]:
            return None, "Rate limit exceeded. Please wait a moment."
        self._requests[user_id].append(now)

        self._check_count += 1
        if self._check_count % 100 == 0:
            stale = [
                k
                for k, v in self._requests.items()
                if not v or (now - max(v)) > 300
            ]
            for k in stale:
                del self._requests[k]

        if not message or not message.strip():
            return None, "Empty message."
        if len(message) > BUSINESS["max_input_length"]:
            return None, f"Message too long (max {BUSINESS['max_input_length']} chars)."

        return message.strip(), None


# ==============================================================================
# LAYER 3: STABILITY
# ==============================================================================


class Health:
    """Track uptime and error rate."""

    def __init__(self) -> None:
        self._start: datetime = datetime.utcnow()
        self._requests: int = 0
        self._errors: int = 0

    def record(self, success: bool) -> None:
        self._requests += 1
        if not success:
            self._errors += 1

    def status(self) -> Dict[str, Any]:
        uptime = (datetime.utcnow() - self._start).total_seconds()
        error_rate = (self._errors / self._requests * 100) if self._requests else 0
        return {
            "status": "healthy" if error_rate < 10 else "degraded",
            "uptime_seconds": int(uptime),
            "requests": self._requests,
            "error_rate": f"{error_rate:.1f}%",
        }


# ==============================================================================
# LAYER 4: SPEED
# ==============================================================================


class Cache:
    """In-memory TTL cache."""

    def __init__(self, max_size: int = 1000) -> None:
        self._data: Dict[str, tuple] = {}
        self._max_size: int = max_size

    def get(self, key: str) -> Any:
        if key in self._data:
            value, expires = self._data[key]
            if expires > time.time():
                return value
            del self._data[key]
        return None

    def set(self, key: str, value: Any, ttl: int = 300) -> None:
        if len(self._data) >= self._max_size:
            now = time.time()
            expired = [k for k, (_, exp) in self._data.items() if exp <= now]
            for k in expired:
                del self._data[k]
            if len(self._data) >= self._max_size:
                to_drop = sorted(self._data.items(), key=lambda x: x[1][1])[
                    : self._max_size // 10
                ]
                for k, _ in to_drop:
                    del self._data[k]
        self._data[key] = (value, time.time() + ttl)


# ==============================================================================
# LAYER 5: REVENUE
# ==============================================================================


class Revenue:
    """Token-gated access and daily usage quotas."""

    def __init__(self, cache: Cache) -> None:
        self._cache = cache
        self._usage: Dict[str, List[str]] = defaultdict(list)

    def get_tier(self, user_address: str) -> str:
        cached = self._cache.get(f"tier:{user_address}")
        if cached is not None:
            return cached
        try:
            r = requests.get(
                f"{AGENTLAUNCH_API}/agents/token/{user_address}", timeout=5
            )
            if r.status_code == 200:
                data = r.json()
                balance = data.get("balance", 0)
                tier = (
                    "premium"
                    if balance >= BUSINESS["premium_token_threshold"]
                    else "free"
                )
                self._cache.set(f"tier:{user_address}", tier, ttl=300)
                return tier
        except Exception:
            pass
        return "free"

    def check_quota(self, user_id: str, tier: str) -> tuple:
        today = datetime.utcnow().date().isoformat()
        self._usage[user_id] = [
            t for t in self._usage[user_id] if t.startswith(today)
        ]
        today_usage = len(self._usage[user_id])
        limit = 1000 if tier == "premium" else BUSINESS["free_requests_per_day"]
        if today_usage >= limit:
            if tier == "free":
                return False, (
                    f"Free limit reached ({limit}/day). "
                    f"Hold {BUSINESS['premium_token_threshold']} tokens for premium!"
                )
            return False, f"Daily limit reached ({limit}/day)."
        self._usage[user_id].append(datetime.utcnow().isoformat())
        return True, None


# ==============================================================================
# AGENTLAUNCH INTEGRATION
# ==============================================================================


class AgentLaunch:
    """Create and manage tokens on AgentLaunch."""

    @staticmethod
    def tokenize() -> Dict:
        agent_address = os.environ.get("AGENT_ADDRESS")
        if not agent_address:
            return {"error": "AGENT_ADDRESS env var not set."}
        try:
            r = requests.post(
                f"{AGENTLAUNCH_API}/agents/tokenize",
                headers={
                    "X-API-Key": os.environ.get("AGENTLAUNCH_API_KEY", ""),
                    "Content-Type": "application/json",
                },
                json={
                    "agentAddress": agent_address,
                    "name": BUSINESS["name"],
                    "description": BUSINESS["description"],
                },
                timeout=30,
            )
            return r.json() if r.status_code in [200, 201] else {"error": r.text}
        except Exception as e:
            return {"error": str(e)}


# ==============================================================================
# TRADING SIGNAL BUSINESS LOGIC
# ==============================================================================


class TradingBotBusiness:
    """
    Moving-average crossover signal generator.

    Collects price data points for each tracked token, computes a simple
    moving average over BUSINESS['signal_window'] samples, then emits
    BUY / SELL / HOLD signals based on the configured thresholds.

    Note: Trading fee is 2% -> 100% to protocol treasury (no creator fee).
    DISCLAIMER: Signals are informational only, not financial advice.
    """

    def __init__(self) -> None:
        self._prices: Dict[str, List[float]] = defaultdict(list)

    def fetch_price(self, token_address: str) -> Optional[float]:
        try:
            r = requests.get(
                f"{AGENTLAUNCH_API}/agents/token/{token_address}", timeout=10
            )
            if r.status_code == 200:
                data = r.json()
                price = (
                    data.get("price")
                    or (data.get("data") or {}).get("price")
                )
                return float(price) if price is not None else None
        except Exception:
            pass
        return None

    def moving_average(self, token_address: str) -> Optional[float]:
        prices = self._prices[token_address]
        window = BUSINESS["signal_window"]
        if len(prices) < 2:
            return None
        sample = prices[-window:]
        return sum(sample) / len(sample)

    def compute_signal(self, token_address: str, current_price: float) -> str:
        ma = self.moving_average(token_address)
        if ma is None:
            n = len(self._prices[token_address])
            needed = max(0, BUSINESS["signal_window"] - n)
            return f"ACCUMULATING DATA ({n} samples, need {needed} more for signal)"

        deviation_pct = ((current_price - ma) / ma) * 100

        if deviation_pct >= BUSINESS["buy_threshold_pct"]:
            return (
                f"BUY SIGNAL — price {deviation_pct:+.2f}% above MA{BUSINESS['signal_window']} "
                f"({current_price:.6f} FET vs MA {ma:.6f} FET)"
            )
        elif deviation_pct <= -BUSINESS["sell_threshold_pct"]:
            return (
                f"SELL SIGNAL — price {deviation_pct:+.2f}% below MA{BUSINESS['signal_window']} "
                f"({current_price:.6f} FET vs MA {ma:.6f} FET)"
            )
        else:
            return (
                f"HOLD — price {deviation_pct:+.2f}% from MA{BUSINESS['signal_window']} "
                f"(threshold: ±{BUSINESS['buy_threshold_pct']}%)"
            )

    async def handle(self, ctx: Context, user_id: str, message: str, tier: str) -> str:
        lower = message.lower()

        # "signal <address>" — compute signal
        if lower.startswith("signal ") or lower.startswith("analyse ") or lower.startswith("analyze "):
            parts = message.split()
            if len(parts) >= 2:
                token_address = parts[1].strip()
                price = self.fetch_price(token_address)
                if price is None:
                    return f"Could not fetch price for {token_address}."
                self._prices[token_address].append(price)
                # Cap history
                if len(self._prices[token_address]) > 200:
                    self._prices[token_address] = self._prices[token_address][-200:]
                signal = self.compute_signal(token_address, price)
                return (
                    f"Token: {token_address[:12]}...\\n"
                    f"Price: {price:.6f} FET\\n"
                    f"Signal: {signal}\\n\\n"
                    f"DISCLAIMER: Informational only, not financial advice."
                )

        return (
            f"Welcome to {BUSINESS['name']}!\\n\\n"
            f"Commands:\\n"
            f"  signal <token_address>   — compute buy/sell/hold signal\\n"
            f"  analyse <token_address>  — alias for signal\\n\\n"
            f"Strategy: MA{BUSINESS['signal_window']} crossover\\n"
            f"Buy threshold: +{BUSINESS['buy_threshold_pct']}% above MA\\n"
            f"Sell threshold: -{BUSINESS['sell_threshold_pct']}% below MA\\n\\n"
            f"DISCLAIMER: Informational only, not financial advice."
        )


# ==============================================================================
# REPLY HELPER
# ==============================================================================


async def reply(ctx: Context, sender: str, text: str, end: bool = False) -> None:
    content = [TextContent(type="text", text=text)]
    if end:
        content.append(EndSessionContent(type="end-session"))
    try:
        await ctx.send(
            sender,
            ChatMessage(timestamp=datetime.utcnow(), msg_id=uuid4(), content=content),
        )
    except Exception as e:
        ctx.logger.error(f"Failed to send reply to {sender[:20]}: {e}")


# ==============================================================================
# MAIN AGENT
# ==============================================================================

cache = Cache(max_size=1000)
security = Security()
health = Health()
revenue = Revenue(cache)
business = TradingBotBusiness()

agent = Agent()
chat_proto = Protocol(spec=chat_protocol_spec)


@chat_proto.on_message(ChatMessage)
async def handle_chat(ctx: Context, sender: str, msg: ChatMessage) -> None:
    try:
        await ctx.send(
            sender,
            ChatAcknowledgement(
                timestamp=datetime.utcnow(), acknowledged_msg_id=msg.msg_id
            ),
        )
    except Exception as e:
        ctx.logger.error(f"Failed to send ack to {sender[:20]}: {e}")

    text = " ".join(
        item.text for item in msg.content if isinstance(item, TextContent)
    ).strip()
    text = text[: BUSINESS["max_input_length"]]

    clean, error = security.check(ctx, sender, text)
    if error:
        health.record(False)
        await reply(ctx, sender, error, end=True)
        return

    Logger.audit(ctx, sender, "request")

    lower = clean.lower()

    if lower in ("help", "?"):
        tier = revenue.get_tier(sender)
        await reply(
            ctx,
            sender,
            f"**{BUSINESS['name']}** v{BUSINESS['version']}\\n\\n"
            f"{BUSINESS['description']}\\n\\n"
            f"Your tier: {tier.upper()}\\n\\n"
            f"Commands: help, status, tokenize, signal <addr>",
        )
        return

    if lower == "status":
        s = health.status()
        await reply(
            ctx,
            sender,
            f"Status: {s['status']} | Uptime: {s['uptime_seconds']}s | "
            f"Requests: {s['requests']} | Error rate: {s['error_rate']}",
        )
        return

    if "tokenize" in lower:
        if OWNER_ADDRESS and sender != OWNER_ADDRESS:
            await reply(ctx, sender, "Only the agent owner can trigger tokenization.", end=True)
            return
        result = AgentLaunch.tokenize()
        link = result.get("data", {}).get("handoff_link") or result.get("handoff_link")
        await reply(
            ctx,
            sender,
            f"Token created! Deploy here: {link}" if link else f"Result: {json.dumps(result)}",
            end=True,
        )
        return

    tier = revenue.get_tier(sender)
    allowed, quota_error = revenue.check_quota(sender, tier)
    if not allowed:
        health.record(False)
        await reply(ctx, sender, quota_error, end=True)
        return

    try:
        response = await business.handle(ctx, sender, clean, tier)
        health.record(True)
    except Exception as e:
        health.record(False)
        Logger.error(ctx, "business_handle", str(e))
        response = "Something went wrong. Please try again."

    await reply(ctx, sender, response, end=True)


@chat_proto.on_message(ChatAcknowledgement)
async def handle_ack(ctx: Context, sender: str, msg: ChatAcknowledgement) -> None:
    ctx.logger.debug(f"Ack from {sender[:20]} for msg {msg.acknowledged_msg_id}")


@agent.on_interval(period=3600)
async def periodic_health(ctx: Context) -> None:
    ctx.logger.info(f"[HEALTH] {json.dumps(health.status())}")


agent.include(chat_proto, publish_manifest=True)

if __name__ == "__main__":
    agent.run()
`,
};
